seml:
  executable: experiment_oc20.py
  name: schnet_oc20_atomic_test
  output_dir: logs_oc20
  project_root_dir: ..

slurm:
  experiments_per_job: 1
  max_simultaneous_jobs: 4  # Restrict number of simultaneously running jobs per job array
  sbatch_options:
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 8-00:00    # max time, D-HH:MM
    partition: gpu_large
    gres: 'gpu:1'
    exclude: gpu15,gpu17,gpu20,mdsi-gpu01,mdsi-gpu02

fixed:
  name: schnet_oc20_atomic_test

  dataset_train:
    - src: /nfs/shared/datasets/oc20/s2ef/2M/train/
      normalize_labels: True
      target_mean: -0.7554450631141663
      target_std: 2.887317180633545
      grad_target_mean: 0.0
      grad_target_std: 2.887317180633545
    - src: /nfs/shared/datasets/oc20/s2ef/all/
      subsampling_fraction: 0.01

  dataset_id:
    - src: /nfs/shared/datasets/oc20/s2ef/2M/train/
      normalize_labels: True
      target_mean: -0.7554450631141663
      target_std: 2.887317180633545
      grad_target_mean: 0.0
      grad_target_std: 2.887317180633545
    - src: /nfs/shared/datasets/oc20/s2ef/all/val_id/
      subsampling_fraction: 0.03
    - src: /nfs/homedirs/oc20_dataset/s2ef/all/test_id/

  dataset_ood_ads:
    - src: /nfs/shared/datasets/oc20/s2ef/2M/train/
      normalize_labels: True
      target_mean: -0.7554450631141663
      target_std: 2.887317180633545
      grad_target_mean: 0.0
      grad_target_std: 2.887317180633545
    - src: /nfs/shared/datasets/oc20/s2ef/all/val_ood_ads/
      subsampling_fraction: 0.03
    - src: /nfs/homedirs/oc20_dataset/s2ef/all/test_ood_ads/

  dataset_ood_cat:
    - src: /nfs/shared/datasets/oc20/s2ef/2M/train/
      normalize_labels: True
      target_mean: -0.7554450631141663
      target_std: 2.887317180633545
      grad_target_mean: 0.0
      grad_target_std: 2.887317180633545
    - src: /nfs/shared/datasets/oc20/s2ef/all/val_ood_cat/
      subsampling_fraction: 0.03
    - src: /nfs/homedirs/oc20_dataset/s2ef/all/test_ood_cat/

  dataset_ood_both:
    - src: /nfs/shared/datasets/oc20/s2ef/2M/train/
      normalize_labels: True
      target_mean: -0.7554450631141663
      target_std: 2.887317180633545
      grad_target_mean: 0.0
      grad_target_std: 2.887317180633545
    - src: /nfs/shared/datasets/oc20/s2ef/all/val_ood_both/
      subsampling_fraction: 0.03
    - src: /nfs/homedirs/oc20_dataset/s2ef/all/test_ood_both/

  logger: tensorboard

  task:
    dataset: trajectory_lmdb
    description: "Regressing to energies and forces for DFT trajectories from OCP"
    type: regression
    metric: mae
    labels:
      - potential energy
    grad_input: atomic forces
    train_on_free_atoms: True
    eval_on_free_atoms: True

  model:
    name: schnet
    hidden_channels: 512
    num_filters: 256
    num_interactions: 4
    num_gaussians: 200
    cutoff: 6.0
    max_neighbors: 50
    use_pbc: True
    atom_to_atom_cutoff: 6.75
    otf_graph: True
    regress_forces: True
    readout: "add"

  # *** Important note ***
  #   The total number of gpus used for this run was 1.
  #   If the global batch size (num_gpus * batch_size) is modified
  #   the lr_milestones and warmup_steps need to be adjusted accordingly.

  optimizer:
    batch_size: 64
    eval_every: 20000
    eval_batch_size: 64
    num_workers: 4
    lr_initial: 0.0001
    lr_gamma: 0.1
    lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
      - 150000
      - 250000
      - 310000
    warmup_steps: 90000
    warmup_factor: 0.2
    max_epochs: 25
    force_coefficient: 33.3
