seml:
  executable: experiment_oe62.py
  name: gemnet_oe62_atomic
  output_dir: logs_oe62
  project_root_dir: ..

slurm:
# Put your own slurm settings here [example below]
  experiments_per_job: 1
  max_simultaneous_jobs: 4  # Restrict number of simultaneously running jobs per job array
  sbatch_options:
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 8-00:00    # max time, D-HH:MM
    partition: gpu_large
    gres: 'gpu:1'

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  name: gemnet_oe62_atomic
  dataset:
    - src: oe62/energy_linref_pbe0/train/pbe0_train.lmdb
    #  For vdw-subtracted PBE0 energies:
    #- src: oe62/energy_linref_pbe0_d3fit/train/pbe0_train.lmdb
      normalize_labels: True
      target_mean: 0.0036029791066818145 #for pbe0 linref energies
      target_std: 1.7420150967007746 #for pbe0 linref energies
      #target_mean: 0.0042125696386549494 #for pbe0 d3fit linref energies
      #target_std: 1.7448031028122666 #for pbe0 d3fit linref energies
    - src: oe62/energy_linref_pbe0/val/pbe0_val.lmdb
    # For vdw-subtracted energies
    #- src: oe62/energy_linref_pbe0_d3fit/val/pbe0_val.lmdb
    - src: oe62/energy_linref_pbe0/test/pbe0_test.lmdb
    # For vdw-subtracted energies
    #- src: oe62/energy_linref_pbe0_d3fit/test/pbe0_test.lmdb


  logger: tensorboard

  task:
    dataset: single_point_lmdb
    description: "Regressing to DFT total energies for structures in OE62"
    type: regression
    metric: mae
    labels:
      - DFT total energy

  model:
    name: gemnet_t
    num_spherical: 7
    num_radial: 128
    num_blocks: 3
    emb_size_atom: 256
    emb_size_edge: 512
    emb_size_trip: 64
    emb_size_rbf: 16
    emb_size_cbf: 16
    emb_size_bil_trip: 64
    num_before_skip: 1
    num_after_skip: 2
    num_concat: 1
    num_atom: 3
    cutoff: 6.0
    max_neighbors: 50
    rbf:
      name: gaussian
    envelope:
      name: polynomial
      exponent: 5
    cbf:
      name: spherical_harmonics
    atom_to_atom_cutoff: 12.0
    extensive: True
    otf_graph: True
    use_pbc: False
    output_init: HeOrthogonal
    activation: silu
    scale_file: scaling_factors_oe62/gemnet_baseline.json

    regress_forces: False
    direct_forces: False

  optimizer:
      batch_size: 8
      eval_batch_size: 8
      eval_every: 10000
      num_workers: 2
      lr_initial: 0.0005
      lr_gamma: 0.1
      lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
        - 750000
        - 1125000
        - 1500000
      warmup_steps: 250000
      warmup_factor: 0.2
      max_epochs: 300
      loss_energy: mae
